openapi: 3.2.0
info:
  title: LawVu Account Teams API
  description: Apis for account related resources (authentication, profiles, organisation details etc)
  version: '1.0'
servers:
- url: https://api-sandbox.lawvu.com/account-apis
  description: Sandbox API
- url: https://api.lawvu.com/account-apis
  description: Production API
tags:
- name: Teams
paths:
  /v1/teams:
    get:
      tags:
      - Teams
      summary: Get teams
      operationId: get-v1-teams
      parameters:
      - name: allowAssigment
        in: query
        description: 'Only return teams that allow work assignment<p>Default: False</p>'
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TeamArray'
              example:
              - id: 1
                name: Team 1
              - id: 2
                name: Team 2
            application/json:
              schema:
                $ref: '#/components/schemas/TeamArray'
              example:
              - id: 1
                name: Team 1
              - id: 2
                name: Team 2
            text/json:
              schema:
                $ref: '#/components/schemas/TeamArray'
              example:
              - id: 1
                name: Team 1
              - id: 2
                name: Team 2
components:
  schemas:
    TeamArray:
      type: array
      items:
        $ref: '#/components/schemas/Team'
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
