openapi: 3.2.0
info:
  title: LawVu Contracts API
  description: The next generation of the LawVu API.
  termsOfService: https://developer.lawvu.com/developer-terms
  contact:
    name: LawVu Developer Support Team
    url: https://developer.lawvu.com
    email: developer@lawvu.com
  version: "1.0"
servers:
- url: https://api-sandbox.lawvu.com
  description: Sandbox API
- url: https://api.lawvu.com
  description: Production API
tags:
- name: Contracts
paths:
  /v2/contracts:
    get:
      tags:
      - Contracts
      summary: Get contracts
      description: Retrieve a list of contracts
      operationId: get-v2-contracts
      parameters:
      - name: $filter
        in: query
        description: Filter the results using OData filter syntax
        schema:
          type: string
      - name: $orderby
        in: query
        description: Order the results using OData orderby syntax
        schema:
          type: string
      - name: $skip
        in: query
        description: Skip the specified number of results
        schema:
          type: integer
      - name: $top
        in: query
        description: Limit the number of results returned
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractCollectionResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Operation 'gt' is not supported for 'Name'
                instance: /contracts
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
    post:
      tags:
      - Contracts
      summary: Create contract
      description: Creates a contract based on the provided contract type.
      operationId: post-v2-contracts
      requestBody:
        content:
          application/json:
            schema:
              required:
              - type
              allOf:
              - $ref: '#/components/schemas/CreateContract'
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: Location to retrieve the created contract
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedContract'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Required
                instance: /contracts/
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The request could not be processed due to a conflict
                errors:
                  ExternalId: Is already in use
                instance: /contracts/
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 409
                title: Conflict
                type: https://api-docs.lawvu.com/errors/conflict
  /v2/contracts/{contractId}:
    get:
      tags:
      - Contracts
      summary: Get contract
      description: Retrieve a contract by its identifier
      operationId: get-v2-contracts-contractid
      parameters:
      - name: contractId
        in: path
        description: The system identifier for the contract
        required: true
        schema:
          type: integer
          description: The system identifier for the contract
          format: int32
          example: 5348
        example: 5348
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contract'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /contracts/5348
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
    patch:
      tags:
      - Contracts
      summary: Update contract
      description: Updates a contracts details
      operationId: patch-v2-contracts-contractid
      parameters:
      - name: contractId
        in: path
        description: The system identifier for the contract
        required: true
        schema:
          type: integer
          description: The system identifier for the contract
          format: int32
          example: 5348
        example: 5348
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateContract'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Required
                instance: /contracts/5348
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: You do not have permission to update this contract
                instance: /contracts/5348
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 403
                title: Forbidden
                type: https://api-docs.lawvu.com/errors/forbidden
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /contracts/5348
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The request could not be processed due to a conflict
                errors:
                  ExternalId: Is already in use
                instance: /contracts/5348
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 409
                title: Conflict
                type: https://api-docs.lawvu.com/errors/conflict
  /v2/contracts/{contractId}/files/{fileId}:
    get:
      tags:
      - Contracts
      summary: Get contract file
      description: Retrieve information about a file on a contract
      operationId: get-v2-contracts-contractid-files-fileid
      parameters:
      - name: contractId
        in: path
        description: The system identifier for the contract
        required: true
        schema:
          type: integer
          description: The system identifier for the contract
          format: int32
          example: 5348
        example: 5348
      - name: fileId
        in: path
        description: The system identifier for the file
        required: true
        schema:
          type: integer
          description: The system identifier for the file
          format: int32
          example: 9456
        example: 9456
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /contracts/5348/files/9456
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
  /v2/contractTypes:
    get:
      tags:
      - Contracts
      summary: Get contract types
      description: Retrieve a list of contract types
      operationId: get-v2-contracttypes
      parameters:
      - name: $skip
        in: query
        description: Specifies the number of items to skip
        schema:
          type: integer
          description: Specifies the number of items to skip
          format: int32
          default: 0
      - name: $top
        in: query
        description: Specifies the maximum number of items to return
        schema:
          type: integer
          description: Specifies the maximum number of items to return
          format: int32
          default: 25
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractTypeCollectionResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                instance: /contractsTypes/
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
components:
  schemas:
    ContractTypeCollectionResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ContractType'
          description: The collection of items
      additionalProperties: false
      description: Response wrapper of a collection of items
    OrganizationReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the organization
          format: int32
          example: 8134
        name:
          type: string
          description: The name of the organization
          readOnly: true
          example: Api Development Organization
      additionalProperties: false
    UserReference:
      type: object
      properties:
        email:
          type: string
          description: The email address of the user
          readOnly: true
          example: api.developer@lawvu.com
        firstName:
          type: string
          description: The first name of the user
          readOnly: true
          example: Api
        id:
          type: string
          description: The unique identifier of the user
          example: f0f1e06e-3005-4093-af7f-1934d55617e1
        lastName:
          type: string
          description: The last name of the user
          readOnly: true
          example: Developer
        organization:
          allOf:
          - $ref: '#/components/schemas/OrganizationReference'
          description: The organization the user belongs to
          readOnly: true
        organizationId:
          type: integer
          description: The system identifier for the organization
          format: int32
          readOnly: true
          example: 8134
      additionalProperties: false
    FileType:
      enum:
      - File
      - Folder
      - ContractDocument
      type: string
      description: The type of file entry
    ResourceReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the resource
          format: int32
          example: 78914
        type:
          allOf:
          - $ref: '#/components/schemas/ResourceType'
          description: The type of the resource
          readOnly: true
          example: Contract
      additionalProperties: false
    CreateContract:
      required:
      - type
      type: object
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/ContractTypeReference'
          description: The type of the contract
        name:
          type:
          - string
          - 'null'
          description: The user defined name of the contract
          example: My contract
        document:
          allOf:
          - $ref: '#/components/schemas/FileReference'
          description: 'The contract document.


            This is only optional if the contract type has a wizard'
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the contract
        expiry:
          type:
          - string
          - 'null'
          description: The expiry date of the contract. The date and time uses the ISO-8601 format and will be in the Local timezone of the organization
          format: date-time
          example: '2024-12-25T00:00:00'
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the contract
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              value: option_1
            my_multioption_field:
            - value: option_a
            - value: option_d
            my_user_field:
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the contract only available to members.


            An indicator where the contract requires membership to access'
          example: false
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this contract is assigned to
      additionalProperties: false
    Contract:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the contract
          format: int32
          readOnly: true
          example: 5348
        name:
          type:
          - string
          - 'null'
          description: The user defined name of the contract
          example: My contract
        document:
          allOf:
          - $ref: '#/components/schemas/FileReference'
          description: The contract document
          readOnly: true
        type:
          allOf:
          - $ref: '#/components/schemas/ContractTypeReference'
          description: The type of the contract
          readOnly: true
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the contract
        expiry:
          type:
          - string
          - 'null'
          description: The expiry date of the contract. The date and time uses the ISO-8601 format and will be in the Local timezone of the organization
          format: date-time
          example: '2024-12-25T00:00:00'
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the contract
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              label: Option 1
              value: option_1
            my_multioption_field:
            - label: Option A
              value: option_a
            - label: Option D
              value: option_d
            my_user_field:
              email: api.developer@lawvu.com
              firstName: Api
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
              lastName: Developer
              organization:
                id: 8134
                name: Api Development Organization
              organizationId: 8134
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the contract only available to members.


            An indicator where the contract requires membership to access'
          default: false
          example: false
        status:
          allOf:
          - $ref: '#/components/schemas/ContractStatus'
          description: The current status of the contract
          example: Active
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this contract is assigned to
        created:
          allOf:
          - $ref: '#/components/schemas/AuditableUserReference'
          description: The user who created the contract and when
          readOnly: true
      additionalProperties: false
    CreatedContract:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the contract
          format: int32
          readOnly: true
          example: 5348
      additionalProperties: false
      description: Represents a contract that has been created
    ResourceType:
      enum:
      - Contract
      - Matter
      type: string
    ContractGroupReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the contract group
          format: int32
          example: 5002
        name:
          type: string
          description: The name of the contract type
          readOnly: true
          example: Employment
      additionalProperties: false
    UpdateContract:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: The user defined name of the contract
          example: My contract
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the contract
        expiry:
          type:
          - string
          - 'null'
          description: The expiry date of the contract. The date and time uses the ISO-8601 format and will be in the Local timezone of the organization
          format: date-time
          example: '2024-12-25T00:00:00'
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the contract
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              value: option_1
            my_multioption_field:
            - value: option_a
            - value: option_d
            my_user_field:
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the contract only available to members.


            An indicator where the contract requires membership to access'
          example: false
        status:
          allOf:
          - $ref: '#/components/schemas/ContractStatus'
          description: The current status of the contract
          example: Active
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this contract is assigned to
      additionalProperties: false
    TeamReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the team
          format: int32
          example: 469
        name:
          type: string
          description: The full name of the team
          readOnly: true
          example: Legal - Commercial
      additionalProperties: false
    ContractType:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the contract type
          format: int32
          readOnly: true
          example: 1234
        name:
          type:
          - string
          - 'null'
          description: The user defined name of the contract type
          example: Contractor Agreement
        parent:
          allOf:
          - $ref: '#/components/schemas/ContractGroupReference'
          description: The parent contract type
        hasWizard:
          type:
          - boolean
          - 'null'
          description: The contract type has a wizard in place.
          example: false
        teamAssignmentRequired:
          type:
          - boolean
          - 'null'
          description: The contract type has a team assignment required.
          example: false
      additionalProperties: false
    HttpValidationProblemDetails:
      type: object
      properties:
        detail:
          type: string
          description: More information about the problem.
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: A dictionary of validation errors, where each key is a field api name and the value is a list of error messages.
        instance:
          type: string
          description: The URI of the resource which the error relates to.
        operationId:
          type: string
          description: A unique trace identifier for the request. This should be provided when requesting support.
        status:
          type: integer
          description: The HTTP status code for the problem.
          format: int32
        title:
          type: string
          description: A short description of the error.
        type:
          type: string
          description: A URI which can be followed to find out more about the problem.
      additionalProperties: {}
    ContractTypeReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the contract type
          format: int32
          example: 1234
        name:
          type: string
          description: The user defined name of the contract type
          readOnly: true
          example: Contractor Agreement
      additionalProperties: false
    ContractStatus:
      enum:
      - Draft
      - Negotiating
      - Approval
      - Signing
      - Executed
      - Expired
      - Void
      type: string
    AuditableReference:
      type: object
      properties:
        dateUtc:
          type: string
          description: The date and time the action was performed. The date and time uses the ISO-8601 format and will be in UTC
          format: date-time
          readOnly: true
          example: '2024-12-25T00:00:00Z'
        userName:
          type: string
          description: The username of who performed the action
          readOnly: true
          example: api.developer@lawvu.com
      additionalProperties: false
    FolderReference:
      type: object
      properties:
        folder:
          allOf:
          - $ref: '#/components/schemas/FolderReference'
          description: "The parent folder. \n\nThe folder will be null when the folder is at the root of the resource"
          readOnly: true
        id:
          type: integer
          description: The system identifier for the folder
          format: int32
          example: 786
        name:
          type: string
          description: The name of the folder
          readOnly: true
          example: Drafts
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        detail:
          type: string
          description: More information about the problem.
        instance:
          type: string
          description: The URI of the resource which the error relates to.
        operationId:
          type: string
          description: A unique trace identifier for the request. This should be provided when requesting support.
        status:
          type: integer
          description: The HTTP status code for the problem.
          format: int32
        title:
          type: string
          description: A short description of the error.
        type:
          type: string
          description: A URI which can be followed to find out more about the problem.
      additionalProperties: {}
    AuditableUserReference:
      type: object
      properties:
        dateUtc:
          type: string
          description: The date and time the action was performed. The date and time uses the ISO-8601 format and will be in UTC
          format: date-time
          readOnly: true
          example: '2024-12-25T00:00:00Z'
        user:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user who performed the action
          readOnly: true
        userName:
          type: string
          description: The username of who performed the action
          readOnly: true
          example: api.developer@lawvu.com
      additionalProperties: false
    ContractCollectionResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Contract'
          description: The collection of items
      additionalProperties: false
      description: Response wrapper of a collection of items
    File:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the file
          format: int32
          readOnly: true
          example: 9456
        name:
          type:
          - string
          - 'null'
          description: 'The user defined name of the file resource

            For file resources with a type of file this includes the file extension'
          example: Standard NDA.docx
        displayId:
          type:
          - string
          - 'null'
          description: 'A system generated identifier of the file resource.

            Also known as "Document ID"'
          readOnly: true
          example: LV0001-0000123.1
        type:
          allOf:
          - $ref: '#/components/schemas/FileType'
          description: The type of file resource
          readOnly: true
          example: File
        folder:
          allOf:
          - $ref: '#/components/schemas/FolderReference'
          description: "The folder where the file resource is located \n\nFolder is null when the file resource is located at the root of the resource"
        contentType:
          type:
          - string
          - 'null'
          description: The content type of the file binary
          readOnly: true
          example: text/plain
        resource:
          allOf:
          - $ref: '#/components/schemas/ResourceReference'
          description: The resource where the file resource is located within
          readOnly: true
        restricted:
          type:
          - boolean
          - 'null'
          description: Is the file resource access restricted
          default: false
          readOnly: true
          example: false
        size:
          type:
          - integer
          - 'null'
          description: The size of the file binary in bytes
          format: int64
          readOnly: true
          example: 18139
        version:
          type:
          - integer
          - 'null'
          description: The version of the file
          format: int32
          readOnly: true
          example: 3
        created:
          allOf:
          - $ref: '#/components/schemas/AuditableUserReference'
          description: The user who created the file resource and when
          readOnly: true
        modified:
          allOf:
          - $ref: '#/components/schemas/AuditableReference'
          description: The username who modified the file resource and when
          readOnly: true
      additionalProperties: false
    UserFieldValue:
      title: User
      type: object
      allOf:
      - $ref: '#/components/schemas/UserReference'
    FileReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the file
          format: int32
          example: 9456
        name:
          type: string
          description: 'The user defined name of the file resource

            For file resources with a type of file this includes the file extension'
          readOnly: true
          example: Standard NDA.docx
        version:
          type: integer
          description: The version of the file
          format: int32
          readOnly: true
          example: 3
      additionalProperties: false
    OptionFieldValue:
      title: Option
      type: object
      properties:
        label:
          type: string
          readOnly: true
          example: Option 1
        value:
          type: string
          example: option_1
x-provenance:
  method: harvested
  publisher: LawVu
  source: https://api-docs.lawvu.com/_bundle/new-api/lawvuapi.openapi.yaml?download
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
