openapi: 3.2.0
info:
  title: LawVu Matters API
  description: The next generation of the LawVu API.
  termsOfService: https://developer.lawvu.com/developer-terms
  contact:
    name: LawVu Developer Support Team
    url: https://developer.lawvu.com
    email: developer@lawvu.com
  version: "1.0"
servers:
- url: https://api-sandbox.lawvu.com
  description: Sandbox API
- url: https://api.lawvu.com
  description: Production API
tags:
- name: Matters
paths:
  /v2/matters:
    get:
      tags:
      - Matters
      summary: Get matters
      description: Retrieve a list of matters
      operationId: get-v2-matters
      parameters:
      - name: $filter
        in: query
        description: Filter the results using OData filter syntax
        schema:
          type: string
      - name: $orderby
        in: query
        description: Order the results using OData orderby syntax
        schema:
          type: string
      - name: $skip
        in: query
        description: Skip the specified number of results
        schema:
          type: integer
      - name: $top
        in: query
        description: Limit the number of results returned
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterCollectionResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Operation 'gt' is not supported for 'Name'
                instance: /matters
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
    post:
      tags:
      - Matters
      summary: Create matter
      description: Creates a matter based on the provided matter type.
      operationId: post-v2-matters
      requestBody:
        content:
          application/json:
            schema:
              required:
              - type
              allOf:
              - $ref: '#/components/schemas/CreateMatter'
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: Location to retrieve the created matter
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedMatter'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Required
                instance: /matters
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The request could not be processed due to a conflict
                errors:
                  ExternalId: Is already in use
                instance: /matters
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 409
                title: Conflict
                type: https://api-docs.lawvu.com/errors/conflict
  /v2/matters/{matterId}:
    get:
      tags:
      - Matters
      summary: Get matter
      description: Retrieve a matter by its identifier
      operationId: get-v2-matters-matterid
      parameters:
      - name: matterId
        in: path
        description: The system identifier for the matter
        required: true
        schema:
          type: integer
          description: The system identifier for the matter
          format: int32
          example: 1056
        example: 1056
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Matter'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /matters/1056
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
    patch:
      tags:
      - Matters
      summary: Update matter
      description: Updates a matters details
      operationId: patch-v2-matters-matterid
      parameters:
      - name: matterId
        in: path
        description: The system identifier for the matter
        required: true
        schema:
          type: integer
          description: The system identifier for the matter
          format: int32
          example: 1056
        example: 1056
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateMatter'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                errors:
                  Name: Required
                instance: /matters/1056
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: You do not have permission to update this matter
                instance: /matters/1056
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 403
                title: Forbidden
                type: https://api-docs.lawvu.com/errors/forbidden
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /matters/1056
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
        '409':
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The request could not be processed due to a conflict
                errors:
                  ExternalId: Is already in use
                instance: /matters/1056
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 409
                title: Conflict
                type: https://api-docs.lawvu.com/errors/conflict
  /v2/matters/{matterId}/files/{fileId}:
    get:
      tags:
      - Matters
      summary: Get matter file
      description: Retrieve information about a file on a matter
      operationId: get-v2-matters-matterid-files-fileid
      parameters:
      - name: matterId
        in: path
        description: The system identifier for the matter
        required: true
        schema:
          type: integer
          description: The system identifier for the matter
          format: int32
          example: 1056
        example: 1056
      - name: fileId
        in: path
        description: The system identifier for the file
        required: true
        schema:
          type: integer
          description: The system identifier for the file
          format: int32
          example: 9456
        example: 9456
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                detail: The requested resource could not be found
                instance: /matters/1056/files/9456
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 404
                title: Resource not found
                type: https://api-docs.lawvu.com/errors/resource_not_found
  /v2/matterTypes:
    get:
      tags:
      - Matters
      summary: Get matter types
      description: Retrieve a list of matter types
      operationId: get-v2-mattertypes
      parameters:
      - name: $skip
        in: query
        description: Specifies the number of items to skip
        schema:
          type: integer
          description: Specifies the number of items to skip
          format: int32
          default: 0
      - name: $top
        in: query
        description: Specifies the maximum number of items to return
        schema:
          type: integer
          description: Specifies the maximum number of items to return
          format: int32
          default: 25
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterTypeCollectionResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HttpValidationProblemDetails'
              example:
                detail: The request was invalid and could not be processed
                instance: /matterTypes/
                operationId: 7edb5d62-f5bf-463b-9410-cdd8b3293d89
                status: 400
                title: Invalid request
                type: https://api-docs.lawvu.com/errors/invalid_request
components:
  schemas:
    UserReference:
      type: object
      properties:
        email:
          type: string
          description: The email address of the user
          readOnly: true
          example: api.developer@lawvu.com
        firstName:
          type: string
          description: The first name of the user
          readOnly: true
          example: Api
        id:
          type: string
          description: The unique identifier of the user
          example: f0f1e06e-3005-4093-af7f-1934d55617e1
        lastName:
          type: string
          description: The last name of the user
          readOnly: true
          example: Developer
        organization:
          allOf:
          - $ref: '#/components/schemas/OrganizationReference'
          description: The organization the user belongs to
          readOnly: true
        organizationId:
          type: integer
          description: The system identifier for the organization
          format: int32
          readOnly: true
          example: 8134
      additionalProperties: false
    OrganizationReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the organization
          format: int32
          example: 8134
        name:
          type: string
          description: The name of the organization
          readOnly: true
          example: Api Development Organization
      additionalProperties: false
    FileType:
      enum:
      - File
      - Folder
      - ContractDocument
      type: string
      description: The type of file entry
    ResourceReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the resource
          format: int32
          example: 78914
        type:
          allOf:
          - $ref: '#/components/schemas/ResourceType'
          description: The type of the resource
          readOnly: true
          example: Contract
      additionalProperties: false
    MatterStatus:
      enum:
      - Draft
      - Scoping
      - Review
      - Active
      - TasksLate
      - MilestonesLate
      - TasksAndMilestonesLate
      - AwaitingManagerAcceptance
      - AwaitingOwnerAcceptance
      - Complete
      - Archived
      - OnHold
      type: string
    MatterTypeReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the matter type
          format: int32
          example: 7492
        name:
          type: string
          description: The user defined name of the matter type
          readOnly: true
          example: NDA
      additionalProperties: false
    ResourceType:
      enum:
      - Contract
      - Matter
      type: string
    MatterManager:
      type: object
      properties:
        intakeQueue:
          allOf:
          - $ref: '#/components/schemas/IntakeQueueReference'
          description: The intake queue for the organization that is assigned to manage the matter
        user:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user who is assigned to manage the matter
      additionalProperties: false
    TeamReference:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the team
          format: int32
          example: 469
        name:
          type: string
          description: The full name of the team
          readOnly: true
          example: Legal - Commercial
      additionalProperties: false
    MatterTypeCollectionResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MatterType'
          description: The collection of items
      additionalProperties: false
      description: Response wrapper of a collection of items
    HttpValidationProblemDetails:
      type: object
      properties:
        detail:
          type: string
          description: More information about the problem.
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: A dictionary of validation errors, where each key is a field api name and the value is a list of error messages.
        instance:
          type: string
          description: The URI of the resource which the error relates to.
        operationId:
          type: string
          description: A unique trace identifier for the request. This should be provided when requesting support.
        status:
          type: integer
          description: The HTTP status code for the problem.
          format: int32
        title:
          type: string
          description: A short description of the error.
        type:
          type: string
          description: A URI which can be followed to find out more about the problem.
      additionalProperties: {}
    AuditableReference:
      type: object
      properties:
        dateUtc:
          type: string
          description: The date and time the action was performed. The date and time uses the ISO-8601 format and will be in UTC
          format: date-time
          readOnly: true
          example: '2024-12-25T00:00:00Z'
        userName:
          type: string
          description: The username of who performed the action
          readOnly: true
          example: api.developer@lawvu.com
      additionalProperties: false
    IntakeQueueReference:
      type: object
      properties:
        organizationId:
          type: integer
          description: The system identifier for the organization
          format: int32
          example: 8134
        organizationName:
          type: string
          description: The name of the organization
          readOnly: true
          example: Api Development Organization
      additionalProperties: false
    CreateMatter:
      required:
      - type
      type: object
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/MatterTypeReference'
          description: The type of the matter
        name:
          type:
          - string
          - 'null'
          description: "The user defined name of the matter \n\nWhen simple ticketing is enabled for the organization then the Name is going to be optional and will default to simple ticketing rules, otherwise is required."
          example: My matter
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the matter
        manager:
          allOf:
          - $ref: '#/components/schemas/MatterManager'
          description: 'The user managing the matter or the intake queue for an organization.


            Only one of User and IntakeQueue can be assigned to a matter at a time.

            '
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the matter
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              value: option_1
            my_multioption_field:
            - value: option_a
            - value: option_d
            my_user_field:
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the matter only available to members


            An indicator where the matter requires membership to access'
          example: false
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this matter is assigned to
      additionalProperties: false
    FolderReference:
      type: object
      properties:
        folder:
          allOf:
          - $ref: '#/components/schemas/FolderReference'
          description: "The parent folder. \n\nThe folder will be null when the folder is at the root of the resource"
          readOnly: true
        id:
          type: integer
          description: The system identifier for the folder
          format: int32
          example: 786
        name:
          type: string
          description: The name of the folder
          readOnly: true
          example: Drafts
      additionalProperties: false
    MatterCollectionResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Matter'
          description: The collection of items
      additionalProperties: false
      description: Response wrapper of a collection of items
    ProblemDetails:
      type: object
      properties:
        detail:
          type: string
          description: More information about the problem.
        instance:
          type: string
          description: The URI of the resource which the error relates to.
        operationId:
          type: string
          description: A unique trace identifier for the request. This should be provided when requesting support.
        status:
          type: integer
          description: The HTTP status code for the problem.
          format: int32
        title:
          type: string
          description: A short description of the error.
        type:
          type: string
          description: A URI which can be followed to find out more about the problem.
      additionalProperties: {}
    AuditableUserReference:
      type: object
      properties:
        dateUtc:
          type: string
          description: The date and time the action was performed. The date and time uses the ISO-8601 format and will be in UTC
          format: date-time
          readOnly: true
          example: '2024-12-25T00:00:00Z'
        user:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user who performed the action
          readOnly: true
        userName:
          type: string
          description: The username of who performed the action
          readOnly: true
          example: api.developer@lawvu.com
      additionalProperties: false
    UpdateMatter:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: "The user defined name of the matter \n\nWhen simple ticketing is enabled for the organization then the Name is going to be optional and will default to simple ticketing rules, otherwise is required."
          example: My matter
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the matter
        manager:
          allOf:
          - $ref: '#/components/schemas/MatterManager'
          description: 'The user managing the matter or the intake queue for an organization.


            Only one of User and IntakeQueue can be assigned to a matter at a time.

            '
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the matter
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              value: option_1
            my_multioption_field:
            - value: option_a
            - value: option_d
            my_user_field:
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the matter only available to members


            An indicator where the matter requires membership to access'
          example: false
        status:
          allOf:
          - $ref: '#/components/schemas/MatterStatus'
          description: The current status of the matter
          example: Active
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this matter is assigned to
      additionalProperties: false
    CreatedMatter:
      type: object
      properties:
        id:
          type: integer
          description: The system identifier for the matter
          format: int32
          readOnly: true
          example: 1056
      additionalProperties: false
      description: Represents a matter that has been created
    MatterType:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the matter type
          format: int32
          readOnly: true
          example: 7492
        name:
          type:
          - string
          - 'null'
          description: The user defined name of the matter type
          example: NDA
        parent:
          allOf:
          - $ref: '#/components/schemas/MatterTypeReference'
          description: The parent matter type
      additionalProperties: false
    File:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the file
          format: int32
          readOnly: true
          example: 9456
        name:
          type:
          - string
          - 'null'
          description: 'The user defined name of the file resource

            For file resources with a type of file this includes the file extension'
          example: Standard NDA.docx
        displayId:
          type:
          - string
          - 'null'
          description: 'A system generated identifier of the file resource.

            Also known as "Document ID"'
          readOnly: true
          example: LV0001-0000123.1
        type:
          allOf:
          - $ref: '#/components/schemas/FileType'
          description: The type of file resource
          readOnly: true
          example: File
        folder:
          allOf:
          - $ref: '#/components/schemas/FolderReference'
          description: "The folder where the file resource is located \n\nFolder is null when the file resource is located at the root of the resource"
        contentType:
          type:
          - string
          - 'null'
          description: The content type of the file binary
          readOnly: true
          example: text/plain
        resource:
          allOf:
          - $ref: '#/components/schemas/ResourceReference'
          description: The resource where the file resource is located within
          readOnly: true
        restricted:
          type:
          - boolean
          - 'null'
          description: Is the file resource access restricted
          default: false
          readOnly: true
          example: false
        size:
          type:
          - integer
          - 'null'
          description: The size of the file binary in bytes
          format: int64
          readOnly: true
          example: 18139
        version:
          type:
          - integer
          - 'null'
          description: The version of the file
          format: int32
          readOnly: true
          example: 3
        created:
          allOf:
          - $ref: '#/components/schemas/AuditableUserReference'
          description: The user who created the file resource and when
          readOnly: true
        modified:
          allOf:
          - $ref: '#/components/schemas/AuditableReference'
          description: The username who modified the file resource and when
          readOnly: true
      additionalProperties: false
    Matter:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          description: The system identifier for the matter
          format: int32
          readOnly: true
          example: 1056
        name:
          type:
          - string
          - 'null'
          description: "The user defined name of the matter \n\nWhen simple ticketing is enabled for the organization then the Name is going to be optional and will default to simple ticketing rules, otherwise is required."
          example: My matter
        displayId:
          type:
          - string
          - 'null'
          description: 'A system generated identifier of the matter.

            Also known as "LawVu ID" or "Matter Number"'
          readOnly: true
          example: LV0001-0001
        type:
          allOf:
          - $ref: '#/components/schemas/MatterTypeReference'
          description: The type of the matter
          readOnly: true
        owner:
          allOf:
          - $ref: '#/components/schemas/UserReference'
          description: The user assigned as the owner of the matter
        manager:
          allOf:
          - $ref: '#/components/schemas/MatterManager'
          description: 'The user managing the matter or the intake queue for an organization.


            Only one of User and IntakeQueue can be assigned to a matter at a time.

            '
        externalId:
          type:
          - string
          - 'null'
          description: A unique user defined identifier that can be used to reference another system
          example: external-01
        fields:
          type:
          - object
          - 'null'
          additionalProperties:
            oneOf:
            - title: 'null'
            - title: Text
              type: string
              example: my text value
            - title: Decimal
              type: number
              example: 78659.84
            - title: Boolean
              type: boolean
              example: true
            - title: Date
              type: string
              example: '2025-05-06'
            - $ref: '#/components/schemas/OptionFieldValue'
            - title: MultiOption
              type: array
              items:
                $ref: '#/components/schemas/OptionFieldValue'
            - $ref: '#/components/schemas/UserFieldValue'
            x-additionalPropertiesName: fieldApiName
          description: The collection of fields associated with the matter
          example:
            my_text_field: my text value
            my_decimal_field: 78659.84
            my_boolean_field: true
            my_date_field: '2025-05-06'
            my_option_field:
              label: Option 1
              value: option_1
            my_multioption_field:
            - label: Option A
              value: option_a
            - label: Option D
              value: option_d
            my_user_field:
              email: api.developer@lawvu.com
              firstName: Api
              id: f0f1e06e-3005-4093-af7f-1934d55617e1
              lastName: Developer
              organization:
                id: 8134
                name: Api Development Organization
              organizationId: 8134
        restricted:
          type:
          - boolean
          - 'null'
          description: 'Is the matter only available to members


            An indicator where the matter requires membership to access'
          default: false
          example: false
        status:
          allOf:
          - $ref: '#/components/schemas/MatterStatus'
          description: The current status of the matter
          example: Active
        teamAssigned:
          allOf:
          - $ref: '#/components/schemas/TeamReference'
          description: The team which this matter is assigned to
        created:
          allOf:
          - $ref: '#/components/schemas/AuditableUserReference'
          description: The user who created the matter and when
          readOnly: true
      additionalProperties: false
    UserFieldValue:
      title: User
      type: object
      allOf:
      - $ref: '#/components/schemas/UserReference'
    OptionFieldValue:
      title: Option
      type: object
      properties:
        label:
          type: string
          readOnly: true
          example: Option 1
        value:
          type: string
          example: option_1
x-provenance:
  method: harvested
  publisher: LawVu
  source: https://api-docs.lawvu.com/_bundle/new-api/lawvuapi.openapi.yaml?download
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
