openapi: 3.2.0
info:
  title: LawVu Contracts Contract Key Date API
  description: Apis for contract resources
  version: '1.0'
servers:
- url: https://api-sandbox.lawvu.com/contract-apis
  description: Sandbox API
- url: https://api.lawvu.com/contract-apis
  description: Production API
tags:
- name: ContractKeyDate
paths:
  /v1/contracts/{contractId}/keyDates:
    get:
      tags:
      - ContractKeyDate
      summary: Get contract key dates
      description: Returns a list of contract key dates
      operationId: get-v1-contracts-contractid-keydates
      parameters:
      - name: contractId
        in: path
        description: The contract id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ContractKeyDateModelArray'
              example:
              - id: 1
                date: '2020-01-01'
                name: Key date 1
                value: 1
              - id: 2
                date: '2020-01-02'
                name: Key date 2
                value: 2
            application/json:
              schema:
                $ref: '#/components/schemas/ContractKeyDateModelArray'
              example:
              - id: 1
                date: '2020-01-01'
                name: Key date 1
                value: 1
              - id: 2
                date: '2020-01-02'
                name: Key date 2
                value: 2
            text/json:
              schema:
                $ref: '#/components/schemas/ContractKeyDateModelArray'
              example:
              - id: 1
                date: '2020-01-01'
                name: Key date 1
                value: 1
              - id: 2
                date: '2020-01-02'
                name: Key date 2
                value: 2
components:
  schemas:
    ContractKeyDateModel:
      type: object
      properties:
        id:
          type: integer
          format: int32
        date:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        value:
          type: number
          format: double
      additionalProperties: false
    ContractKeyDateModelArray:
      type: array
      items:
        $ref: '#/components/schemas/ContractKeyDateModel'
