openapi: 3.2.0
info:
  title: LawVu Invoices API
  description: Apis for invoice resources
  version: '1.0'
servers:
- url: https://api-sandbox.lawvu.com/invoice-apis
  description: Sandbox API
- url: https://api.lawvu.com/invoice-apis
  description: Production API
tags:
- name: Invoices
paths:
  /v1/invoices:
    get:
      tags:
      - Invoices
      summary: Get invoices
      operationId: get-v1-invoices
      parameters:
      - name: skip
        in: query
        description: The number of invoices to skip (used for paging)
        schema:
          type: integer
          format: int32
      - name: filtering.field
        in: query
        description: Field to filter by (optional)
        schema:
          type: string
      - name: filtering.operator
        in: query
        description: Operator used for filtering (optional)
        schema:
          enum:
          - eq
          - neq
          - lt
          - lte
          - gt
          - gte
          - startswith
          - endswith
          - contains
          - doesnotcon
          - isnull
          type: string
      - name: filtering.value
        in: query
        description: Value to filter by (optional)
        schema:
          type: string
      - name: sorting.direction
        in: query
        description: Set the sorting direction
        schema:
          enum:
          - asc
          - desc
          type: string
      - name: sorting.field
        in: query
        description: Set the sorting fields
        schema:
          type: string
      - name: take
        in: query
        description: 'The maximum number of invoices to return<p>Default: 50</p>'
        schema:
          type: integer
          format: int32
          default: 50
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/InvoiceDataSourceResult'
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDataSourceResult'
            text/json:
              schema:
                $ref: '#/components/schemas/InvoiceDataSourceResult'
  /v1/invoices/{invoiceId}:
    patch:
      tags:
      - Invoices
      summary: Update invoice
      operationId: patch-v1-invoices-invoiceid
      parameters:
      - name: invoiceId
        in: path
        description: The invoice Id
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        description: The update definition (json patch)
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/OperationArray'
          application/json:
            schema:
              $ref: '#/components/schemas/OperationArray'
          text/json:
            schema:
              $ref: '#/components/schemas/OperationArray'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OperationArray'
      responses:
        '200':
          description: Success
  /v1/invoices/recipients:
    get:
      tags:
      - Invoices
      summary: Retrieve Invoice Recipients
      operationId: get-v1-invoices-recipients
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillingRecipient'
              example:
              - id: 1
                name: Jeff
                addressLine1: 123 Sesame Street
                addressLine2: Narnia
                addressLine3: Antarctica
                taxType: GST
                taxNumber: '4'
                contactName: Bill
                contactPhone: '17'
                contactEmail: emailaddress@gmail.com
              - id: 2
                name: Steve
                addressLine1: 124 Sesame Street
                addressLine2: South Narnia
                addressLine3: Antarctica
                taxType: TAX
                taxNumber: '40'
                contactName: Stan
                contactPhone: '71'
                contactEmail: anotheremailaddress@gmail.com
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillingRecipient'
              example:
              - id: 1
                name: Jeff
                addressLine1: 123 Sesame Street
                addressLine2: Narnia
                addressLine3: Antarctica
                taxType: GST
                taxNumber: '4'
                contactName: Bill
                contactPhone: '17'
                contactEmail: emailaddress@gmail.com
              - id: 2
                name: Steve
                addressLine1: 124 Sesame Street
                addressLine2: South Narnia
                addressLine3: Antarctica
                taxType: TAX
                taxNumber: '40'
                contactName: Stan
                contactPhone: '71'
                contactEmail: anotheremailaddress@gmail.com
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillingRecipient'
              example:
              - id: 1
                name: Jeff
                addressLine1: 123 Sesame Street
                addressLine2: Narnia
                addressLine3: Antarctica
                taxType: GST
                taxNumber: '4'
                contactName: Bill
                contactPhone: '17'
                contactEmail: emailaddress@gmail.com
              - id: 2
                name: Steve
                addressLine1: 124 Sesame Street
                addressLine2: South Narnia
                addressLine3: Antarctica
                taxType: TAX
                taxNumber: '40'
                contactName: Stan
                contactPhone: '71'
                contactEmail: anotheremailaddress@gmail.com
components:
  schemas:
    InvoiceDataSourceResult:
      type: object
      properties:
        data:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Invoice'
          description: Represents a single page of processed data.
        total:
          type: integer
          description: The total number of records available.
          format: int32
      additionalProperties: false
    OperationArray:
      type: array
      items:
        $ref: '#/components/schemas/Operation'
    Invoice:
      type: object
      properties:
        id:
          type: integer
          format: int32
        invoiceNo:
          type:
          - string
          - 'null'
        invoiceDate:
          type:
          - string
          - 'null'
          format: date-time
        dueDate:
          type:
          - string
          - 'null'
          format: date-time
        disbursements:
          type:
          - number
          - 'null'
          format: double
        fees:
          type:
          - number
          - 'null'
          format: double
        otherFees:
          type:
          - number
          - 'null'
          format: double
        fileId:
          type:
          - integer
          - 'null'
          format: int32
        status:
          type:
          - string
          - 'null'
        fileName:
          type:
          - string
          - 'null'
        batchId:
          type: integer
          format: int32
        thirdParty:
          type: boolean
        paid:
          type:
          - boolean
          - 'null'
        paidDateUtc:
          type:
          - string
          - 'null'
          format: date-time
        paymentNote:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        matterId:
          type:
          - integer
          - 'null'
          format: int32
        approvedDateUtc:
          type:
          - string
          - 'null'
          format: date-time
        purchaseOrderNo:
          type:
          - string
          - 'null'
        totalTax:
          type:
          - number
          - 'null'
          format: double
        approvedFees:
          type:
          - number
          - 'null'
          format: double
        currency:
          type:
          - string
          - 'null'
        postedDateUtc:
          type:
          - string
          - 'null'
          format: date-time
        internalNotes:
          type:
          - string
          - 'null'
        billingPeriodStart:
          type:
          - string
          - 'null'
          format: date-time
        billingPeriodEnd:
          type:
          - string
          - 'null'
          format: date-time
        serviceProviderName:
          type:
          - string
          - 'null'
        serviceProviderId:
          type:
          - string
          - 'null'
      additionalProperties: false
    Operation:
      type: object
      properties:
        value:
          type:
          - object
          - 'null'
        path:
          type:
          - string
          - 'null'
        op:
          type:
          - string
          - 'null'
        from:
          type:
          - string
          - 'null'
      additionalProperties: false
    BillingRecipient:
      type: object
      properties:
        id:
          type:
          - integer
          - 'null'
          format: int32
        name:
          type:
          - string
          - 'null'
        addressLine1:
          type:
          - string
          - 'null'
        addressLine2:
          type:
          - string
          - 'null'
        addressLine3:
          type:
          - string
          - 'null'
        taxType:
          enum:
          - GST
          - TAX
          - VAT
          type:
          - string
          - 'null'
          description: <p>Options:</p><ul><li>GST</li><li>TAX</li><li>VAT</li></ul>
        taxNumber:
          type:
          - string
          - 'null'
        contactName:
          type:
          - string
          - 'null'
        contactPhone:
          type:
          - string
          - 'null'
        contactEmail:
          type:
          - string
          - 'null'
      additionalProperties: false
